export const INCREMENT = "INCREMENT";

export const DECREMENT = "DECREMENT";

export const ADDTASKINTODO = "ADDTASKINTODO";

export const REMOVEFROMTODO = "REMOVEFROMTODO";

export const ADDTASKINDOING = "ADDTASKINDOING";

export const REMOVEFROMDOING = "REMOVEFROMDOING";

export const ADDTASKINDONE = "ADDTASKINDONE";

export const REMOVEFROMDONE = "REMOVEFROMDONE";
